#!/bin/bash
#
# GLPI install script
# Author: PapyPoc & Poupix
# Version: 1.5.0
# Main file
# Langage pris en compte français et anglais
#

# Nettoyer le terminal
clear
source /root/glpi_install/config # Fichier de variable
source /root/glpi_install/function # Fichier de fonctions
load_language # Fichier de langue
check_root # Utilisateur root
check_dialog # Regarde si dialog est installé
check_distro # Regarde si la distribution est conforme
check_install "${REP_GLPI}" # Regarde si GLPI est installé ou pas
display_result # Affiche le résultat de l'installation
clear